### ISSUE TITLE
你好，使用词向量vec模式时，百度网盘地址不可用了

### ISSUE THREAD

**Issue by topbat** [ofooo/FAQrobot#7]
百度网盘地址不可用了，请再提供下有效地址，或者备注下如何生成那些文件，谢谢。

**Comment by yaleimeng** [comment]
可以使用[自己训练的词向量](https://pan.baidu.com/s/1LuAJDh9T7xhBPmy6v8jE8Q) 代替。网络上也有不少预训练的词向量可下载。
二进制模型有3个文件，一个扩展名是.model，两个扩展名是.npy。

**Comment by topbat** [comment]
好的呢，谢谢。
